package com.agentops.firewall.policy;

import com.agentops.firewall.common.domain.enums.ActionType;
import com.agentops.firewall.common.domain.enums.PolicyOutcome;
import com.agentops.firewall.common.domain.enums.RiskLevel;

/**
 * Test-only helper that mirrors the V3 Flyway migration so policy tests
 * running against H2 (where Flyway is disabled) see the same seeded
 * policy set as a real Postgres deployment. IDs are generated by
 * Hibernate; tests look up policies by their unique name.
 */
final class SamplePolicySeeder {

    private SamplePolicySeeder() {
    }

    static void seed(PolicyRepository policies, PolicyConditionRepository conditions) {
        Policy lowAllow = save(policies, "Allow LOW-risk actions",
                10, PolicyOutcome.ALLOW, null, null);
        addCondition(conditions, lowAllow, "riskLevel", "EQUALS", "LOW");

        Policy denyReadSecret = save(policies, "Deny READ_SECRET",
                100, PolicyOutcome.DENY, ActionType.READ_SECRET, null);

        Policy approveDeleteFile = save(policies, "Require approval for DELETE_FILE",
                80, PolicyOutcome.NEEDS_APPROVAL, ActionType.DELETE_FILE, null);

        Policy approveDeployCode = save(policies, "Require approval for DEPLOY_CODE",
                80, PolicyOutcome.NEEDS_APPROVAL, ActionType.DEPLOY_CODE, null);

        Policy denyExternalApi = save(policies, "Deny non-allowlisted external API calls",
                90, PolicyOutcome.DENY, ActionType.CALL_EXTERNAL_API, null);
        addCondition(conditions, denyExternalApi,
                "metadata.targetDomain", "NOT_IN",
                "[\"acme.com\",\"internal\",\"trusted-partner.com\"]");

        Policy approveExternalEmail = save(policies, "Require approval for external email with attachment",
                70, PolicyOutcome.NEEDS_APPROVAL, ActionType.SEND_EMAIL, null);
        addCondition(conditions, approveExternalEmail,
                "metadata.containsAttachment", "EQUALS", "true");
        addCondition(conditions, approveExternalEmail,
                "metadata.recipientDomain", "NOT_IN", "[\"acme.com\",\"internal\"]");

        Policy denyCustomerData = save(policies, "Deny customer-data access at HIGH risk",
                95, PolicyOutcome.DENY, ActionType.ACCESS_CUSTOMER_DATA, RiskLevel.HIGH);

        Policy approveTerminal = save(policies, "Require approval for non-allowlisted terminal commands",
                85, PolicyOutcome.NEEDS_APPROVAL, ActionType.RUN_TERMINAL_COMMAND, null);
        addCondition(conditions, approveTerminal,
                "metadata.commandType", "NOT_IN", "[\"ls\",\"echo\",\"pwd\",\"cat\"]");

        Policy approveWriteDb = save(policies, "Require approval for WRITE_DATABASE",
                85, PolicyOutcome.NEEDS_APPROVAL, ActionType.WRITE_DATABASE, null);

        Policy approveInfraPr = save(policies, "Require approval for infrastructure GitHub PRs",
                80, PolicyOutcome.NEEDS_APPROVAL, ActionType.CREATE_GITHUB_PR, null);
        addCondition(conditions, approveInfraPr,
                "metadata.modifiesInfrastructure", "EQUALS", "true");

        // Silence unused-variable warnings for entities we did not need to reference further.
        java.util.Objects.requireNonNull(lowAllow);
        java.util.Objects.requireNonNull(denyReadSecret);
        java.util.Objects.requireNonNull(approveDeleteFile);
        java.util.Objects.requireNonNull(approveDeployCode);
        java.util.Objects.requireNonNull(denyCustomerData);
        java.util.Objects.requireNonNull(approveWriteDb);
    }

    private static Policy save(PolicyRepository policies, String name, int priority,
                                PolicyOutcome effect, ActionType actionType, RiskLevel minRisk) {
        Policy policy = new Policy();
        policy.setName(name);
        policy.setPriority(priority);
        policy.setEffect(effect);
        policy.setEnabled(true);
        policy.setActionType(actionType);
        policy.setMinRiskLevel(minRisk);
        return policies.save(policy);
    }

    private static void addCondition(PolicyConditionRepository conditions, Policy parent,
                                      String field, String operator, String value) {
        PolicyCondition c = new PolicyCondition();
        c.setPolicyId(parent.getId());
        c.setField(field);
        c.setOperator(operator);
        c.setValue(value);
        conditions.save(c);
    }
}